name: neATL20_fixed
library: natLCOE
weather: northeast_atlantic_swh_100m_6yrs.csv
service_equipment: [ctv1_20.yaml, ctv2_20.yaml, ctv3_20.yaml, ctv4_20.yaml, ctv5_20.yaml, cable_lay1.yaml, cable_lay2.yaml, hlv1.yaml, hlv2.yaml, rmt.yaml]
layout: 15MW_layout_fixed.csv
inflation_rate: 0
fixed_costs: fixed_costs.yaml
workday_start: 6
workday_end: 18
start_year: 2017
end_year: 2022
project_capacity: 1005
