name: soATL_fixed_SOV
library: natLCOE
weather: southern_atlantic_swh_100m_6yrs.csv
service_equipment: [sov1.yaml, sov2.yaml, sov3.yaml, sov4.yaml, sov5.yaml, sov6.yaml, sov7.yaml, sov8.yaml, sov9.yaml, sov10.yaml, sov11.yaml, sov12.yaml, sov13.yaml, sov14.yaml, sov15.yaml, sov16.yaml, sov17.yaml, sov18.yaml, hlv1.yaml, hlv2.yaml, cable_lay1.yaml, cable_lay2.yaml, rmt.yaml]
layout: 15MW_layout_fixed_SOV.csv
inflation_rate: 0
fixed_costs: fixed_costs.yaml
workday_start: 6
workday_end: 18
start_year: 2017
end_year: 2022
project_capacity: 1005
