# Site + Plant Parameters
site:
  depth: 170
  distance: 148
  distance_to_landfall: 130
plant:
  layout: ring
  num_turbines: 67
  row_spacing: 7
  substation_distance: 1
  turbine_spacing: 7
port:
  monthly_rate: 2000000.0
  sub_assembly_lines: 1
  turbine_assembly_cranes: 1
# Vessels
array_cable_install_vessel: example_cable_lay_vessel
export_cable_install_vessel: example_cable_lay_vessel
mooring_install_vessel: example_support_vessel
oss_install_vessel: floating_heavy_lift_vessel
ahts_vessel: example_ahts_vessel
support_vessel: example_support_vessel
towing_vessel: example_towing_vessel
towing_vessel_groups:
  ahts_vessels: 1
  station_keeping_vessels: 2
  towing_vessels: 3
wtiv: floating_heavy_lift_vessel
# Module Specific
substructure:
  takt_time: 168
array_system:
  free_cable_length: 0.5
array_system_design:
  cables:
  - XLPE_185mm_66kV
  - XLPE_630mm_66kV
export_system_design:
  cables: HVDC_2000mm_320kV
  percent_added_length: 0.0
substation_design:
  floating_oss: True
mooring_system_design:
  num_lines: 3
  drag_embedment_fixed_length: 0
# Configured Phases
design_phases:
- ArraySystemDesign
- ElectricalDesign # New electrical design module includes export cable, offshore substation, and onshore substation design
- SemiSubmersibleDesign
- MooringSystemDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 0
  MooredSubInstallation: 0
  MooringSystemInstallation: 0
  FloatingSubstationInstallation: 0
# Project Inputs
turbine: 15MW_generic
